### ISSUE TITLE
Usability: scant user feedback on add wrap

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#191]
When performing e.g. `o add-wrap newtonsoft.json`, it takes a long time for the add-wrap call to return and a lot of that time is spent waiting after reading "Trying to add package". Arch Linux' pacman has a nice way of notifying; showing progress bars and asking about dependencies (and stating their sizes) before adding.

Also; `o add-wrap` feels slow (takes more than a minute to run every time) for new packages.

**Comment by serialseb** [comment]
add-wrap is slow because you have nuget most probably, as package lists are not cached in 1.0, this is addressed by the 1.1 implementation of caches, see #9.

The lack of async feedback falls into the category of async messages and is scheduled for 1.2 (see #73)

Closing as issues alread reported and tracked. Reopen if something has been missed.
